version: "3.7"

services:

  web: # frontend - ReactJS
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_BACKEND_SECRET_KEY=${BACKEND_SECRET_KEY}
        - REACT_APP_API_URL=${API_URL}
    container_name: ask_web
    command: nginx -g "daemon off;"
    environment:
      VIRTUAL_HOST: localhost
    ports:
      - 8080:80
    networks:
      - frontend

  api: # backend - Ruby
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: ask_api
    command: bundle exec rackup --host 0.0.0.0 -p 3000
    environment:
      VIRTUAL_HOST: api.localhost
      BACKEND_SECRET_KEY:
      SLACK_WEBHOOK_URL:
      PROJECT_NAME:
      PROJECT_ENV:
      CORS_ALLOW_ORIGIN:
    expose:
      - "3000"
    networks:
      - backend

  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: ask_nginx_proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      #- /etc/nginx/htpasswd:/etc/nginx/htpasswd
      #- /etc/nginx/vhost.d:/etc/nginx/vhost.d
      #- /etc/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
