# Common.mk rev. 20210725

# Tested with GNU Make 3.81
# Warn when an undefined variable is referenced
MAKEFLAGS += --warn-undefined-variables
# Default to modern shell
SHELL := bash
# Remove dangling files on error
.DELETE_ON_ERROR:

# Tested with GNU Make 4.3
# Eliminate use of the built-in implicit rules
MAKEFLAGS += --no-builtin-rules
# Fail fast & loud for easier debugging
.SHELLFLAGS := -euo pipefail -c

.PHONY: all
# Show help when no target specified
all: help

TARGET_MAX_CHAR_NUM := 24

.PHONY: help
#%% Show available targets (this screen)
help:
	@echo 'Usage:'
	@echo '  make <target>'
	@echo ''
	@echo 'Targets:'
	@cat $(MAKEFILE_LIST) | awk '/^[a-zA-Z\-_0-9.]+:/ { \
		helpMessage = match(lastLine, /^#%% (.*)/); \
		if (helpMessage) { \
			helpCommand = substr($$1, 0, index($$1, ":")-1); \
			helpMessage = substr(lastLine, RSTART + 3, RLENGTH); \
			printf "  %-$(TARGET_MAX_CHAR_NUM)s %s\n", helpCommand, helpMessage; \
		} \
	} \
	{ lastLine = $$0 }'

.PHONY: print-var
#%% Debug make variable (e.g. make print-CURDIR)
print-var:
# Just an empty command for autogenerated help;
# the command below brings the real value

print-%:
	@echo '$* = $($*)'

.PHONY: pre-commit-run
#%% pre-commit: Run tests
pre-commit-run:
	pre-commit run -c .pre-commit-config.yaml --files ./**/*

.PHONY: pre-commit-install
#%% pre-commit: Install git hooks
pre-commit-install:
	pre-commit install

.PHONY: pre-commit-uninstall
#%% pre-commit: Uninstall git hooks
pre-commit-uninstall:
	pre-commit uninstall

.PHONY: lint
#%% Run linters
lint: pre-commit-run
